---
# tasks file for mongodb

  - name: Load JSON file into a MongoDB
    joelwking.mongodb.mongodb_iq:
        host: "{{ mongodb_hostname }}"
        username: "{{ mongodb_username }}"
        password: "{{ mongodb_password }}"
        port: "{{ mongodb_port }}"
        #
        database:  "{{ database }}"
        collection: "{{ collection }}"
        document: "{{ lookup('file', filename) }}"
