---
# tasks file for mongodb

  - name: Query document from MongoDB
    joelwking.mongodb.mongodb_iq:
        host: "{{ mongodb_hostname }}"
        username: "{{ mongodb_username }}"
        password: "{{ mongodb_password }}"
        port: "{{ mongodb_port }}"
        #
        database:  "{{ mongodb_database }}"
        collection: "{{ mongodb_collection }}"
        query: "{{ mongodb_query }}"
        